# Generated by Django 4.1.1 on 2022-10-26 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="email_address",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="author",
            name="first_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="author",
            name="last_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="caption",
            field=models.ManyToManyField(to="blog.tag"),
        ),
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.TextField(
                default="", validators=[django.core.validators.MinLengthValidator(10)]
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post", name="date", field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="post",
            name="excerpt",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="image_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="", unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="caption",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
