# Generated by Django 4.1.1 on 2022-11-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_author_email_address_author_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="image_name",),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(null=True, upload_to="posts"),
        ),
    ]
